@startuml

allow_mixing

node WebSocket {
    component "Socket.io.Client" as sioc
}

node "Chat Server(Tornado||Node)" as chatserver {
    component "Socket.io.Server" as sios
}
node "Main Server(Django)" as mainserver {
    component "Celery Client" as celeryclient
}



node "Celery Workers(N)(CONSUMER)" as celeryworkers


node "RabbitMQ(QUEUES)" as r

database QUEUES as queues {
    class "socket.io" as sioqueue {

    }
}

database PostgreSQL as psql {
}

sioc <--> sios : connection

sios <--> sioqueue : produce/publish
r <--> queues : messages delivery
r --> celeryworkers : messages delivery
mainserver --> psql : request data
celeryclient ---> sioqueue : publish
celeryworkers ---> psql: save results
@enduml